controller_manager_ns: controller_manager
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
controller_names:
  - panda_arm_hand_controller

panda_arm_hand_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
    - panda_finger_joint1
    - panda_finger_joint2
