controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    panda_arm_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
        - panda_finger_joint1
        - panda_finger_joint2
      command_interfaces:
        - position
        - velocity
      state_interfaces:
        - position
        - velocity
