# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    # - arm_controller
    # - gripper_controller
    - panda_arm_hand_controller

  # arm_controller:
  #   type: FollowJointTrajectory
  #   joints:
  #     - panda_joint1
  #     - panda_joint2
  #     - panda_joint4
  #     - panda_joint5
  # gripper_controller:
  #   type: FollowJointTrajectory
  #   joints:
  #     - panda_finger_joint1
  panda_arm_hand_controller:
    type: FollowJointTrajectory
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint4
      - panda_joint5
      - panda_finger_joint1